### ISSUE TITLE
BBC BASIC for Microcontrollers

### ISSUE THREAD

**Issue by OzHawk** [rtrussell/BBCSDL#8] opened 2021-07-12 02:27 UTC
Hi Richard,
Sorry to raise this as an issue, but GitHub still doesn't have a good communication/discussion area setup for projects.

I was wanted to know whether anyone has taken your source and adapted it for the 32bit microcontrollers that are available, like the STM32 or ESP32, or maybe even the new Raspberry Pi Pico?

Specifically, I have been looking for a version of BASIC than will run on the ESP32 and output to VGA using the FabGL library.

The closests thing I have come across is this
https://github.com/paulscottrobson/eris
but Paul has used an emulated homegrown processor that makes modifications difficult.  I like that your interpreter is written in 'C' and is easy to follow.

I had my first exposure to BBC BASIC a few years ago when I started developing for my Amstrad NC100.  I love the structured nature of the language.

I have an interest in the ESP32 as a stand alone modern retro computer, something that someone can assemble themselves from cheap readily available parts and program in BASIC.

Regards,
Mike Hawkey

**Comment by Rob-McKay** [comment] 2021-07-12 07:14
Hi Mike,

I did get the command line version up and running on a SAME70.

It is do-able. 

I needed to dummy out quite a few functions but I did get it to a state where I could run a program but as it was running in a bare-metal environment I had no way to load / save programs due to a lack of file system etc.

I dropped this project due to lack of time.

Regards,

Rob

**Comment by OzHawk** [comment] 2021-07-12 08:01
Thanks Rob.
Were you outputting to VGA, or were you using the USB/Serial interface for input and output?

The FabGL library includes methods for accessing an SD card.

**Comment by rtrussell** [comment] 2021-07-12 08:31
> I like that your interpreter is written in 'C' and is easy to follow.

It's not very 'portable' C though.  It makes some assumptions that may not be valid in a microcontroller environment (e.g. that 'int' is 32-bit) and also depends on some features and extensions of **gcc** that, whilst accurately reproduced by **clang**, may not be by other compilers.  Then there's a reliance on non-aligned loads working, which may not be the case on all architectures.

So there are some gotchas which might catch you out if you attempt a port to a microcontroller.  If a side-effect of any work you might do is to make the code more portable, all to the good.

**Comment by OzHawk** [comment] 2021-07-12 13:20
Thanks for the info Richard.  The microcontrollers I'm considering are all 32 bit, so the 'int' issue may not be a problem.  The smaller 8 bit constrained microcontrollers are more suited to Tiny BASIC.

I'm not sure what you mean by "non-aligned loads".  Are you refering to the alignment of structures?

I think both the ESP32 and STM32 can use a version of the **gcc** compiler, so this may eliminate some of the compatibility issues.

From a 'bare-metal' implementation, I would be insterested in your option about how to implement the graphics library into BBC BASIC.  The idea is to have the machine boot straight into the immediate mode, with the FabGL graphics library handling input and output.

**Comment by Rob-McKay** [comment] 2021-07-12 13:28
Hi Mike,

> Were you outputting to VGA, or were you using the USB/Serial interface for input and output?

I was using the serial port.

**Comment by OzHawk** [comment] 2021-07-12 13:30
There is an interesting thread here
https://www.thebackshed.com/forum/ViewTopic.php?FID=16&TID=11941
comparing MMBASIC with BBC BASIC.  It looks like he was running it on a Raspberry Pi Zero though, and had the RISCOS underneath.

**Comment by rtrussell** [comment] 2021-07-12 14:26
> I'm not sure what you mean by "non-aligned loads".

Compilers tend to assume (reasonably enough) that 'ordinary' scalar variables are declared in C code and that therefore alignment is guaranteed by the compiler.  But to maximise compatibility with _BBC BASIC for Windows_ I use an assembly-language module (variously **bbdata_arm_xx.s** or **bbdata_x86_xx.nas**) to declare them, so 'natural' alignment is not guaranteed.  This isn't generally an issue with modern CPUs because they can usually handle unaligned addresses, albeit with a performance penalty, but could be with microcontrollers.

Probably you are not too concerned with low-level compatibility with BB4W and BBCSDL so you could replace the assembler module with one coded in C, then the issue would largely go away.  But I mentioned it as something to be aware of.

> I would be interested in your option about how to implement the graphics library into BBC BASIC.

Have you looked at the graphic in the README.md?  That illustrates how the various modules are divided between the 'generic' interpreter and the platform-specific parts.  Generally speaking, when porting BBC BASIC to another platform you must customise all input-output by writing your own replacements for the latter.  So for example the Console Mode editions have one set of such files and the SDL 2.0 editions another:

![Architecture](https://www.bbcbasic.co.uk/bbcsdl/arch.png)

As far as graphics specifically are concerned, one decision you would need to make is whether to support the low-level 'VDU interface' whereby graphics are output by sending sequences of bytes to the 'VDU stream'.  Advantages of adhering to that interface are compatibility, of course, and the ease with which you can move the graphics drivers into a separate thread or process, onto a separate CPU (c.f. the BBC Micro's Second Processors) or even to a remote terminal via a serial or network link.  But, equally, there is an overhead in having to decode those VDU commands at the receiving end.

**Comment by rtrussell** [comment] 2021-08-22 21:17
It may be somewhat relevant to this discussion that [Eric Olson](https://www.raspberrypi.org/forums/memberlist.php?mode=viewprofile&u=104329) is porting BBC BASIC to the Raspberry Pi Pico, which uses an ARM Cortex-M0+ CPU and may qualify as a 'microcontroller'.  Although there are some ongoing issues, this is apparently substantially working, and shows that some of my concerns about it running successfully on such a platform have proved to be unfounded.

**Comment by rtrussell** [comment] 2021-09-15 21:43
With Eric's permission I have merged the Pico version into this repository, so it should hopefully now be easier to port BBC BASIC to other microcontrollers.  For example **littlefs** has been added as a dependency, so this should simplify incorporating a filesystem.  There is some ongoing discussion about the structure of the repository, so there may yet be some refactoring.

**Comment by OzHawk** [comment] 2021-09-16 04:00
Having had an initial look, I'm not sure that porting this to the ESP32 is within my current abilities, however I am watching this space closely as I would dearly like to see it done.
I made another ESP32 developer aware of this project in the hopes that he may take on the porting effort.  He has previously developeed his own 16bit BASIC interpreter for the ESP32. https://github.com/paulscottrobson

**Comment by OzHawk** [comment] 2021-09-20 03:05
Looking at your structure a bit more, I see the FabGL implementation as a blend of the microcontroller version and the SDL version.  It will need to implement the screen/VDU modules of the SDL edition, and the microcontroller changes of the Pico version.
I'm going to raise it as a new issue.

**Comment by rtrussell** [comment] 2021-09-23 10:29
With Eric Olson's Console Mode edition for the Pico now being largely complete (apart from the assembler), and Memotech-Bill actively working on a VGA GUI edition for the Pico, I will close this issue now.

**Closed as completed by rtrussell** 2021-09-23 10:29 UTC
