### ISSUE TITLE
Can´t save a file

### ISSUE THREAD

**Issue by bodhi-baum** [rtrussell/BBCSDL#5] opened 2021-02-03 09:57 UTC
When I enter something in SDLIDE and then try to save, an internal error 206 message pops up and the program crashes without saving. 

In BBCEdit everything works correctly.
I use the Linux binary, btw.

**Comment by rtrussell** [comment] 2021-02-03 10:07
Error 206 is 'Bad directory'.  Please check the directory into which you are trying to save, is there anything unusual about it?  For example does it have any non-ASCII characters in the directory name?  Can you provide instructions for how to reproduce the error?

**Comment by bodhi-baum** [comment] 2021-02-03 10:26
Well, no directories are displayed for selection at all, but the error 206 is displayed directly, without. having a possibility to change anything.

**Comment by bodhi-baum** [comment] 2021-02-03 10:41
I can also provide a hardcopy which maybe makes it clearer.
![SDLIDE error 206](https://user-images.githubusercontent.com/5256377/106735623-c545d800-6614-11eb-8cd0-cf4d6352511e.png)

**Comment by rtrussell** [comment] 2021-02-03 11:50
Unfortunately I cannot reproduce the issue here.  What version of Linux are you using?  This is what should happen when you try to Save:
![scrot](https://user-images.githubusercontent.com/42455052/106742975-ac89f200-6615-11eb-89ac-64508632698d.png)

**Comment by bodhi-baum** [comment] 2021-02-03 12:00
I use Linux Mint 20.1, 64 Bit, which is an Ubuntu derivat. What is strange is, that within BBCEdit there are no problems at all, saving a file,
And in SDLIDE the only window which appears is the error message but no selection window.

**Comment by bodhi-baum** [comment] 2021-02-03 12:05
I just saw that we use different versions of SDLIDE - can you provide me the version you are using? To be on the same level, so to say.

**Comment by rtrussell** [comment] 2021-02-03 12:05
I expect the difference between BBCEdit and SDLIDE is the default directory it initially selects.  BBCEdit seems to default to the directory containing BBCEdit itself; SDLIDE defaults to the directory in the **@usr$** variable.  Can you please try this.  Click on the 'keyboard' icon in the toolbar (or select **Run... Immediate Mode** from the menu).  This should open a new immediate-mode window.  In that window please type **PRINT @usr$** and tell me what it prints:

![usrdir](https://user-images.githubusercontent.com/42455052/106744294-79e0f900-6617-11eb-9b36-0a412d714cfd.png)

**Comment by bodhi-baum** [comment] 2021-02-03 12:12
![SDLIDE I](https://user-images.githubusercontent.com/5256377/106745547-8702e580-6621-11eb-94da-709d2b2a60da.png)

**Comment by rtrussell** [comment] 2021-02-03 12:23
OK, that looks right.  I was hoping to see something unusual!   Can you check that the directory displayed there actually exists and is writable, for example by doing this from a standard Linux shell prompt:

```
cd /home/bodhi/.local/share/BBCBasic/
touch test
```

**Comment by bodhi-baum** [comment] 2021-02-03 12:28
Looks good....
![SDLIDE II](https://user-images.githubusercontent.com/5256377/106747099-bd416480-6623-11eb-9f12-bfd35f681bea.png)

**Comment by rtrussell** [comment] 2021-02-03 12:58
At least we're eliminating possibilities!   What happens if you do **File... Load** rather than File Save...?  Do you now see a file selector, or does the Error 206 happen again?

**Comment by bodhi-baum** [comment] 2021-02-03 13:02
if I do File... Load I see the file selector.

**Comment by rtrussell** [comment] 2021-02-03 13:10
OK, good, so we know that the file selector itself works.   Try loading any of the example programs; assuming it loads successfully try saving it again (**File... Save As**).  Does that work or do you now get Error 206 again?

**Comment by bodhi-baum** [comment] 2021-02-03 13:27
Loading a file works. When I try to save it, I can only select Save as.. which also works.

**Comment by rtrussell** [comment] 2021-02-03 15:12
OK, so try making an insignificant edit to the example program you loaded (e.g. add or delete a space at the start of the line).  That should enable the **Save** menu item that was failing for you before.  Does it work?

**Comment by bodhi-baum** [comment] 2021-02-03 15:22
That did work.

**Comment by rtrussell** [comment] 2021-02-03 15:44
OK, so now clear the program you loaded (**File... New**), type in the program you wrote before, and try to save that.  Have these steps resolved the issue, at least temporarily?

**Comment by bodhi-baum** [comment] 2021-02-03 15:54
Yes indeed, now it was possible for me to save the file and even the file selector showed up.

Do you have any idea, what could have caused the prior behaviour?

**Comment by rtrussell** [comment] 2021-02-03 16:15
Not really.  The symptom suggests it was defaulting either to a non-existent directory or to a directory that requires root access.  I'm guessing it was some sort of initialisation glitch, but in any case I should probably modify the code so that it is protected against that eventuality, whatever the cause.

**Comment by bodhi-baum** [comment] 2021-02-03 16:29
Hope you can fix it.

**Comment by rtrussell** [comment] 2021-02-03 17:23
I can easily protect it against an invalid directory (so it won't report an error and abort) but since I've no idea why the directory was invalid in the first place I can't fix that.  It will be interesting to see if anybody else encounters the same thing.  I'll close this issue in the hope they don't!

**Closed as completed by rtrussell** 2021-02-03 17:23 UTC
